version: '3.9'
services:
  db:
    image: container-registry.oracle.com/database/express:21.3.0-xe # container-registry.oracle.com/database/express:latest
    container-name: oracle-xe
    environment:
        ORACLE_PWD: YourStrongPassw0rd
    ports:
        - "1521:1521"
    networks:
      - backend

networks:
  backend:
    driver: bridge
