version: "3.9"
services:
  db:
    build:
      context: /var/home/steven/Documents/Podman/Postgres
      dockerfile: /var/home/steven/Documents/Podman/Postgres/Dockerfile.postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dvdrental
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  gis:
    build:
      context: /var/home/steven/Documents/Podman/Postgres
      dockerfile: /var/home/steven/Documents/Podman/Postgres/Dockerfile.gis
    restart: always
    environment:
      POSTGRES_PASSWORD: postgis
      POSTGRES_USER: postgis
      POSTGRES_DB: postgis
    ports:
      - "5433:5432"
    volumes:
      - gis_data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "15432:80"
    depends_on:
      - db
    volumes:
      - pg_data:/var/lib/pgadmin
    networks:
      - backend

volumes:
  postgres_data:
  pg_data:
  gis_data:

networks:
  backend:
    driver: bridge
